[package]
name = "ckb-test-chain-utils"
version = "0.17.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-core = { path = "../../core" }
ckb-db = { path = "../../db" }
ckb-hash = { path = "../hash" }
ckb-store = { path = "../../store" }
ckb-chain-spec = { path = "../../spec" }
ckb-dao-utils = { path = "../dao/utils" }
ckb-traits = { path = "../../traits" }
lazy_static = "1.3.0"
tempfile = "3.0"
faketime = "0.2.0"
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
