[package]
name = "ckb-service"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"
lazy_static = "1.0"
